sudo: required
dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - nschloe/eigen-backports
    packages:
      - g++-6
      - gcc-6
      - libeigen3-dev
      - libboost-dev

install:
  - export CXX="g++-6" CC="gcc-6" OMP_NUM_THREADS=2

compiler:
  - gcc

script:
  - cmake .
  - cmake --build . --target ctests
  - bin/ctests
